### ISSUE TITLE
Script crashes when connection to Namecheap cannot be established

### ISSUE THREAD

**Issue by iesou** [EdwardChamberlain/namecheap_ddns#6]
**Describe the bug**
Best I can tell, the script receives a error 104 Connection reset by peer, and crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure Namecheap DDNS script
2. Turn on the docker
3. Wait for connection to be reset and watch it fail.

**Expected behaviour**
Was hoping the error handling would attempt to restart the loop at this point and try again.

**Screenshots / Logs**
Here are the docker logs from the incident
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:s

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
raise six.reraise(type(error), error, _stacktrace)

File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/main.py", line 19, in <module>
res = get(f"https://dynamicdns.park-your-domain.com/update?host={os.environ['APP_HOST']}&domain={os.environ['APP_DOMAIN']}&password={os.environ['APP_PASSWORD']}")
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Desktop (please complete the following information):**
 - OS: UnRaid 6.9.2
 - Version: Current

**Additional context**
More than happy to provide more info if needed, please just let me know what I missed.
Thank you for putting this together btw.

**Comment by EdwardChamberlain** [comment]
Thanks for raising this.

I have pushed an update to the development branch that will prevent the crashing. Would you mind trying that and seeing if this fixes your issue? You can switch to the development branch by changing the repository (in the edit docker page) to "edchamberlain/namecheap_ddns:development".

A HTTP 104 error is a serverside error where the server responds with a RST packet to drop the connection so is an odd one to see and probably not related to this docker! Have you got a DDNS record set up on your Namecheap account, are you using your DDNS password (and not the Namecheap pass), and is your firewall blocking the connection?

**Comment by iesou** [comment]
I am using your dev branch version now. I will let it run for a few days and let you know if it stops.

The odd thing about all this is that it works most of the time. I could connect with the prod version and update the IP regularly, it just seems that every once in a while the server closes the connection. Because of this, I don't think it's anything related to the config or my firewall, something going on with the routing to Namecheap perhaps?

**Comment by iesou** [comment]
No errors in the past few days, I'll keep an eye on it though.

**Comment by EdwardChamberlain** [comment]
Thanks for the update. I will close this issue now but if you have any more issues feel free to reopen it!
